CREATE SEQUENCE IF NOT EXISTS account_number_seq
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

ALTER TYPE account_type ADD VALUE IF NOT EXISTS 'WITHDRAWAL';
ALTER TYPE account_type ADD VALUE IF NOT EXISTS 'DEPOSIT';